import logging
from event_manager import Observer

# Configure the logging module
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


class Logger(Observer):
    def update(self, event, data):
        if event == "signal_generated":
            logging.info(f"Signal generated by {data['strategy']}: {data['data'].tail(1)}")